{
 "title": "Certificates",
 "description": "A Grafana Dashboard for visualizing the data collected by the x509_cert Telegraf plugin for InfluxDB.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "x509_cert", "label": "x509_cert datasource", "query": "influxdb" },
   {
    "name": "zone",
    "query": "SHOW TAG VALUES ON \"ssl_certs_info\" WITH KEY = \"zone\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES ON \"ssl_certs_info\" WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "Invalid certificates",
   "type": "table",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_SSL_CERTS_INFO}\")\n  |> range(start: $timeFrom, stop: $timeTo)\n  |> filter(fn: (r) => r._measurement == \"x509_cert\")\n  |> filter(fn: (r) => r.environment =~ /$environment/ and r.zone =~ /$zone/ and r.verification == \"invalid\")\n  |> group(columns: [\"source\", \"serial_number\"])\n  |> sort(columns: [\"_time\"])\n  |> keep(columns: [\"startdate\", \"enddate\", \"expiry\", \"verification_error\", \"verification_code\", \"source\", \"serial_number\"])\n  |> unique(column: \"serial_number\")\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Certificate  expiration list",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_SSL_CERTS_INFO}\")\n  |> range(start: $timeFrom, stop: $timeTo)\n  |> filter(fn: (r) => r._measurement == \"x509_cert\")\n  |> filter(fn: (r) => r.environment =~ /$environment/ and r.zone =~ /$zone/)\n  |> group(columns: [\"source\", \"serial_number\"])\n  |> sort(columns: [\"_time\"])\n  |> keep(columns: [\"startdate\", \"enddate\", \"expiry\", \"verification_error\", \"verification_code\", \"source\", \"serial_number\"])\n  |> unique(column: \"serial_number\")\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Certificate  details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_SSL_CERTS_INFO}\")\n  |> range(start: $timeFrom, stop: $timeTo)\n  |> filter(fn: (r) => r._measurement == \"x509_cert\")\n  |> filter(fn: (r) => r.environment =~ /$environment/ and r.zone =~ /$zone/)\n  |> group(columns: [\"source\", \"common_name\", \"country\", \"issuer_common_name\", \"locality\", \"organization\", \"organizational_unit\", \"province\", \"public_key_algorithm\", \"signature_algorithm\", \"serial_number\", \"san\"])\n  |> sort(columns: [\"_time\"])\n  |> keep(columns: [\"expiry\", \"source\", \"common_name\", \"country\", \"issuer_common_name\", \"locality\", \"organization\", \"organizational_unit\", \"province\", \"public_key_algorithm\", \"signature_algorithm\", \"serial_number\", \"san\"])\n  |> unique(column: \"serial_number\")\n  |> limit(n:1)"
    }
   ]
  }
 ]
}