{
 "title": "System Metrics Dashboard",
 "tags": [ "os" ],
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/schema\" schema.tagValues(bucket: \"bucketakke\", tag: \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.cpu.usage\") |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000.0 }))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.memory.usage\")"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\")) |> filter(fn: (r) => r._measurement == \"host.storage.mount.space.free\") |> map(fn: (r) => ({ r with _value: float(v: r._value) }) ) |> map(fn: (r) => ({ r with _value: r._value / 1024.0 / 1024.0 / 1024.0 }))",
     "alias": "Free Space (GB)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 64, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.cpu.usage\")",
     "alias": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 64, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.memory.usage\")",
     "alias": "Memory Usage"
    }
   ]
  },
  {
   "title": "Network Data Read/Write",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 72, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.network.data.read\")",
     "alias": "Data Read"
    },
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.network.data.write\")",
     "alias": "Data Write"
    }
   ]
  },
  {
   "title": "Swap Metrics (Stacked)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 80, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.swap.usage\")",
     "alias": "Swap Usage"
    },
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") ) |> filter(fn: (r) => r._measurement == \"host.swap.free\")",
     "alias": "Swap Free"
    }
   ]
  },
  {
   "title": "process.cpu.usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"process.cpu.usage\")"
    }
   ]
  },
  {
   "title": "process.hiccups",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"process.hiccups\")"
    }
   ]
  },
  {
   "title": "process.ulimit.file-descriptors.max",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"process.ulimit.file-descriptors.max\")"
    }
   ]
  },
  {
   "title": "process.ulimit.file-descriptors.used",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"process.ulimit.file-descriptors.used\")"
    }
   ]
  },
  {
   "title": "kamon.trace.sampler.decisions",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"kamon.trace.sampler.decisions\")"
    }
   ]
  }
 ]
}