{
 "title": "JVM Metrics Dashboard",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/schema\" schema.tagValues(bucket: \"bucketakke\", tag: \"host\")"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "import \"influxdata/influxdb/schema\" schema.tagValues(bucket: \"bucketakke\", tag: \"service\")"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Utilization",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") and (r.service =~ /$service/ or \"$service\" == \".*\")) |> filter(fn: (r) => r._measurement == \"jvm.memory.utilization\")"
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") and (r.service =~ /$service/ or \"$service\" == \".*\")) |> filter(fn: (r) => r._measurement == \"jvm.gc\")",
     "alias": "JVM GC"
    }
   ]
  },
  {
   "title": "Hiccups",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") and (r.service =~ /$service/ or \"$service\" == \".*\")) |> filter(fn: (r) => r._measurement == \"process.hiccups\")",
     "alias": "Hiccups"
    }
   ]
  },
  {
   "title": "JVM Threads States",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") and (r.service =~ /$service/ or \"$service\" == \".*\")) |> filter(fn: (r) => r._measurement == \"jvm.threads.states\")",
     "alias": "JVM Threads States"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Used",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucketakke\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => (r.host =~ /$host/ or \"$host\" == \".*\") and (r.service =~ /$service/ or \"$service\" == \".*\")) |> filter(fn: (r) => r._measurement == \"jvm.memory.pool.used\")",
     "alias": "JVM Memory Pool Used"
    }
   ]
  }
 ]
}